version: '3.6'

services:
  ##### zookeeper - node0 #####
  zookeeper0:
    image: zookeeper:3.4.12
    restart: unless-stopped
    hostname: zoo0
    ports:
      - 2181:2181  # client port
    env_file:
      zoo.env
    volumes:
      - ./zoo/data:/data
      - ./zoo/datalog:/datalog
  
  ##### kafka - single broker #####
  kafka0:
    image: confluentinc/cp-kafka:4.1.1
    hostname: kafka0
    ports:
      - 9092:9092  # client port
    env_file:
      kafka.env
    volumes:
      - ./kafka-single/data0:/var/lib/kafka/data

  ##### kafka schema registry #####
  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:4.1.1
    hostname: kafka-schema-registry
    restart: unless-stopped
    ports:
      - 9071:8081
    env_file:
      schema_registry.env
    depends_on:
      - zoo0
      - kafka0

  ##### kafka rest proxy #####  
  image: confluentinc/cp-kafka-rest:4.1.0
    hostname: kafka-rest-proxy
    ports:
      - 9072:8082
    env_file:
      rest_proxy.env
    depends_on:
      - zoo0
      - kafka0
      - kafka-schema-registry

  ##### kafka topics ui #####
    image: landoop/kafka-topics-ui:0.9.3
    hostname: kafka-topics-ui
    ports:
      - 9070:8000
    env_file:
      topics_ui.env
    depends_on:
      - zoo0
      - kafka0
      - kafka-schema-registry
      - kafka-rest-proxy
